# This is a basic workflow to help you get started with Actions
name: Remove old artifacts

on:
  schedule:
    # Every sunday at 1am
    - cron: "0 1 * * 0"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 day'
